#' Generates a table of mixed effects
#' models from a list of models generated by a call to [fitMixedEffectsModels()].
#'
#' The ordering of the table is determined by the fixed effects
#' argument passed to [fitMixedEffectsModels()]. Generally,
#' if there is an interaction term, that p-value is used, otherwise
#' the other fixed effects, usually `TimePoint`.
#'
#' @order 2
#' @rdname fitMixedEffectsModels
#' @param x A list of mixed-effects models calculated
#' using [fitMixedEffectsModels()]. Alternatively, an object of
#' class `"mixed_effects_table"` for the S3 print method.
#' @return A list object of class `mixed_effects_table` with the
#' following components:
#' \item{stat.table}{A data frame (table) of the results:
#' \describe{
#'   \item{Time effect:}{Both F-values and p-values for TimePoint}
#'   \item{Group effect:}{Both F-values and p-values for Group}
#'   \item{p.value:}{Unadjusted p-values for the KS-distances}
#'   \item{fdr:}{FDR adjustment to p-values}
#'   \item{p.bonferroni:}{Bonferroni corrected p-value}
#'   \item{rank:}{Ranking by the test significance.}
#' }}
#' \item{test}{The name of the model fit, "Linear Mixed-effects Model".}
#' \item{call}{The direct call made the [fitMixedEffectsModels()].}
#' \item{data.dim}{The dimensions of the data frame.}
#' \item{method}{The fitting method used by `lme`.}
#' \item{fixed}{The fixed-effects.}
#' \item{observations}{The number of total observations.}
#' \item{PIDfield}{The field name identifying the subjects in the data frame.}
#' \item{subjects}{The number of subjects.}
#' @author Stu Field
#' @examples
#' # `soma_lme` class object
#' class(models)
#'
#' # create table from `soma_lme` object
#' lme_tab <- createMixedEffectsTable(models)
#' @importFrom tibble as_tibble deframe
#' @importFrom tidyr pivot_longer unite
#' @importFrom stats p.adjust anova runif setNames
#' @importFrom dplyr sym mutate arrange row_number select everything
#' @importFrom dplyr ends_with starts_with filter row_number bind_rows
#' @importFrom SomaDataIO col2rn rn2col addClass
#' @export
createMixedEffectsTable <- function(x) {

  stopifnot(
    inherits(x, "soma_lme"), # our own object `fitMixedEffectsModels()`
    !is.null(names(x))       # must be a named list
  )

  if ( !"fixed" %in% names(attributes(x)) ) {
    stop(
      "Fixed effects string missing. ",
      "Was the model list created using `fitMixedEffectsModels()`?",
      call. = FALSE
    )
  }

  stab <- lapply(x, function(.x) {
    aov_tab <- stats::anova(.x) |>
      data.frame() |>
      dplyr::select(-ends_with("DF")) |>
      as_tibble(rownames = "metric") |>
      dplyr::filter(row_number() != 1)  # 1st row is `Intercept`
    # don't want `Parameter` name
    pivot_longer(aov_tab, -metric) |>
      unite(col = "name", -value) |>
      deframe() |> as.list()  |> data.frame() |>
      dplyr::select(starts_with("Response_"),
                    starts_with("TimePoint_"),
                    everything()) |>   # reorder to group F/p-vals
      cbind(converged = .x$converged)  # add converged bool
  }) |>
    dplyr::bind_rows(.id = "AptName")

  p_col <- gsub("\\*", ".", attr(x, "fixed")) |> # replace '*' with '.'
    paste0("_p.value$") |>                  # paste to end with p-value
    grep(names(stab), value = TRUE) |>      # search `stab` for a match
    dplyr::sym()                            # convert to symbol for !! below

  stab <- dplyr::mutate(stab,
                        fdr          = p.adjust(!!p_col, method = "fdr"), # nolint
                        p.bonferroni = p.adjust(!!p_col, method = "bonferroni")
  ) |>
    dplyr::arrange(!!p_col) |>
    dplyr::mutate(rank = dplyr::row_number()) |>
    col2rn("AptName")

  ret.list <- list()
  ret.list$stat.table   <- stab
  ret.list$test         <- "Linear Mixed-effects Model"
  ret.list$call         <- x[[1L]]$call
  ret.list$method       <- x[[1L]]$method
  ret.list$fixed        <- attributes(x)$fixed
  ret.list$random       <- attributes(x)$random
  ret.list$log          <- attributes(x)$log
  ret.list$nModels      <- length(x)
  ret.list$data.dim     <- attributes(x)$data.dim
  dims                  <- x[[1L]]$dims
  ret.list$observations <- dims$N
  pids                  <- dims$ngrps[dims$Q[1L]]
  ret.list$PIDfield     <- attributes(x)$PIDfield
  ret.list$subjects     <- unname(pids)
  if ( withr::with_preserve_seed(runif(1) < 0.25) ) somaPraise()
  ret.list |>
    addClass(c("stat_table", "mixed_effects_table"))
}

#' @order 3
#' @describeIn fitMixedEffectsModels
#' There is a S3 print method for `mixed_effects_table` class.
#'
#' @param n Numeric. The number of rows to show in the S3 print method.
#' @param ... Additional arguments as required by default S3 print methods.
#' @examples
#' # S3 print method
#' lme_tab
#'
#' @export
print.mixed_effects_table <- function(x, n = 6, ...) {
  left <- c("Fixed effects",
            "Random effects",
            "Number of models",
            "Subject field",
            "Number of subjects",
            "Number of observations") |> pad(25)
  right <- c(x$fixed, x$random, x$nModels, x$PIDfield, x$subjects, x$observations)
  writeLines(paste(" ", left, right))
  cat("\n")
  writeLines(signal_rule("Stat Table", line_col = "blue"))
  print(utils::head(x$stat.table, n))
  invisible(x)
}


#' @order 4
#' @describeIn fitMixedEffectsModels
#' The S3 `writeStatTable()` method for `mixed_effects_table` class.
#'
#' @param file A file name to write table output, typically a `*.csv`.
#' @examples
#' # S3 writeStatTable method
#' f_out <- tempfile("lme-table-", fileext = ".csv")
#' writeStatTable(lme_tab, file = f_out)
#' @export
writeStatTable.mixed_effects_table <- function(x, file) {   # nolint
  withr::local_output_sink(file, append = TRUE)
  cat("Optim method,", x$method, "\n", sep = "")
  cat("Fixed effects,", x$fixed, "\n", sep = "")
  cat("Random effects,", x$random, "\n", sep = "")
  cat("Subject field,", x$PIDfield, "\n", sep = "")
  cat("Number of subjects,", x$subjects, "\n", sep = "")
  cat("Number of observations,", x$observations, "\n\n", sep = "")
  renameStatTable(x$stat.table) |> rn2col("AptName") |>
    format(digits = 7L) |>
    write_uni_table(file = file)
  invisible(file)
}
